export const trailReports = [
  {
    id: 1,
    title: "Buckskin Gulch",
    description:
      "Backpack Buckskin Gulch & Paria Canyon: a 45-mile journey through epic slots",
    slug: "buckskin-gulch",
    featuredImage: {
      url: "https://res.cloudinary.com/dlle6kl4n/image/upload/v1762471738/DSCF9483_bxzeyq.webp",
      alt: "Man and dog buckskin gulch",
    },
    author: "Brenden Togioka",
    category: "backpacking",
    location: "Arizona/Utah, USA",
    content:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Praesentium dicta soluta, temporibus reiciendis quaerat culpa. Quia consequatur quisquam odio doloremque similique temporibus magni voluptatem nobis, id beatae animi officia sequi unde molestiae libero. Quibusdam, minus. Doloribus in, aut, repudiandae commodi assumenda tenetur excepturi a ipsam illum molestias dolore, rem et nostrum libero vero sit iusto sapiente voluptas magni quaerat aliquid mollitia. Quas corporis fugiat ducimus dolorum. Omnis nulla iste cumque dolores dignissimos nam pariatur nihil id suscipit nobis! Inventore unde nulla corrupti architecto ea quia incidunt in ad error minus quo, cumque quasi eos nihil aliquid est aspernatur laborum animi officia iusto? Consectetur quis ratione vitae vel! Assumenda vitae maxime eum consequatur harum! Sed fuga atque, consequuntur tempore unde quam repudiandae praesentium in? Nemo quia cum, ducimus est corporis, magnam eum et natus tenetur id debitis distinctio iste dolores, recusandae fugit voluptatibus veniam eos voluptates soluta adipisci ipsum? Repudiandae magni natus, hic est dolor qui numquam fuga rem repellat porro quos dolores enim commodi, quae reiciendis laborum et inventore nam quo voluptas autem nisi obcaecati illo soluta! Non velit accusamus soluta quas, ducimus ullam asperiores architecto saepe hic nulla distinctio culpa fugiat labore illo laboriosam, fugit molestias officia excepturi at iste doloribus. Neque beatae doloremque provident atque rerum facere. Provident, repellendus iusto sequi aliquam quas tempora at nobis est quasi quibusdam quae fuga quidem in fugit aut, exercitationem aperiam deserunt hic veritatis! Rem impedit a dolorum possimus inventore natus fugiat incidunt praesentium ratione, nostrum quisquam aperiam blanditiis quia culpa libero deleniti est suscipit beatae alias minus, perspiciatis quo saepe quas! Fuga, cupiditate numquam ex, distinctio eligendi saepe eos placeat harum hic quod ea! Quibusdam iusto, dolor similique doloremque doloribus pariatur consequuntur itaque? Excepturi accusamus architecto soluta eveniet illum delectus autem iste, iure obcaecati vel, vitae totam ex, id voluptatem. Illo, sequi ad nostrum praesentium animi exercitationem pariatur cum quis nam tempora quam illum rerum voluptatum molestiae beatae repellendus architecto voluptatem numquam voluptas? Iure quia aliquam tenetur in animi laborum totam cupiditate numquam provident consequatur unde perspiciatis mollitia quibusdam doloremque ut minima, similique a quis tempore optio esse dolorum! A nobis corrupti, vel exercitationem labore veritatis aliquid dolorum vitae quidem et iste adipisci esse quos iusto dolor provident possimus tempore eum asperiores nostrum laborum, velit explicabo aperiam. Numquam blanditiis aliquid, quae porro labore, minus perferendis deserunt vitae consequatur impedit obcaecati repellat! Vitae magni laborum est aliquid, neque temporibus reprehenderit animi accusamus?",
  },
  {
    id: 2,
    title: "Aurora Borealis in Fairbanks",
    description:
      "Chase the Aurora Borealis in Fairbanks, Alaska — nature’s most magical light show",
    slug: "aurora-fairbanks",
    featuredImage: {
      url: "https://res.cloudinary.com/dlle6kl4n/image/upload/t_Banner 16:9/v1757649729/Alaska/DSCF7663-Enhanced-NR_uib3xj.jpg",
      alt: "Aurora borealis in Alaska",
    },
    author: "Brenden Togioka",
    category: "travel",
    location: "Alaska, USA",
    content:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Praesentium dicta soluta, temporibus reiciendis quaerat culpa. Quia consequatur quisquam odio doloremque similique temporibus magni voluptatem nobis, id beatae animi officia sequi unde molestiae libero. Quibusdam, minus. Doloribus in, aut, repudiandae commodi assumenda tenetur excepturi a ipsam illum molestias dolore, rem et nostrum libero vero sit iusto sapiente voluptas magni quaerat aliquid mollitia. Quas corporis fugiat ducimus dolorum. Omnis nulla iste cumque dolores dignissimos nam pariatur nihil id suscipit nobis! Inventore unde nulla corrupti architecto ea quia incidunt in ad error minus quo, cumque quasi eos nihil aliquid est aspernatur laborum animi officia iusto? Consectetur quis ratione vitae vel! Assumenda vitae maxime eum consequatur harum! Sed fuga atque, consequuntur tempore unde quam repudiandae praesentium in? Nemo quia cum, ducimus est corporis, magnam eum et natus tenetur id debitis distinctio iste dolores, recusandae fugit voluptatibus veniam eos voluptates soluta adipisci ipsum? Repudiandae magni natus, hic est dolor qui numquam fuga rem repellat porro quos dolores enim commodi, quae reiciendis laborum et inventore nam quo voluptas autem nisi obcaecati illo soluta! Non velit accusamus soluta quas, ducimus ullam asperiores architecto saepe hic nulla distinctio culpa fugiat labore illo laboriosam, fugit molestias officia excepturi at iste doloribus. Neque beatae doloremque provident atque rerum facere. Provident, repellendus iusto sequi aliquam quas tempora at nobis est quasi quibusdam quae fuga quidem in fugit aut, exercitationem aperiam deserunt hic veritatis! Rem impedit a dolorum possimus inventore natus fugiat incidunt praesentium ratione, nostrum quisquam aperiam blanditiis quia culpa libero deleniti est suscipit beatae alias minus, perspiciatis quo saepe quas! Fuga, cupiditate numquam ex, distinctio eligendi saepe eos placeat harum hic quod ea! Quibusdam iusto, dolor similique doloremque doloribus pariatur consequuntur itaque? Excepturi accusamus architecto soluta eveniet illum delectus autem iste, iure obcaecati vel, vitae totam ex, id voluptatem. Illo, sequi ad nostrum praesentium animi exercitationem pariatur cum quis nam tempora quam illum rerum voluptatum molestiae beatae repellendus architecto voluptatem numquam voluptas? Iure quia aliquam tenetur in animi laborum totam cupiditate numquam provident consequatur unde perspiciatis mollitia quibusdam doloremque ut minima, similique a quis tempore optio esse dolorum! A nobis corrupti, vel exercitationem labore veritatis aliquid dolorum vitae quidem et iste adipisci esse quos iusto dolor provident possimus tempore eum asperiores nostrum laborum, velit explicabo aperiam. Numquam blanditiis aliquid, quae porro labore, minus perferendis deserunt vitae consequatur impedit obcaecati repellat! Vitae magni laborum est aliquid, neque temporibus reprehenderit animi accusamus?",
  },
  {
    id: 3,
    title: "Bisti Badlands",
    description:
      "Explore Bisti Badlands, New Mexico — surreal hoodoos, alien landscapes, endless wonder",
    slug: "bisti-badlands",
    featuredImage: {
      url: "https://res.cloudinary.com/dlle6kl4n/image/upload/t_Banner 16:9/v1701835601/Bisti/5_lyuv2l.png",
      alt: "Hoodoos in Bisti",
    },
    author: "Brenden Togioka",
    category: "explore",
    location: "New Mexico, USA",
    content:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Praesentium dicta soluta, temporibus reiciendis quaerat culpa. Quia consequatur quisquam odio doloremque similique temporibus magni voluptatem nobis, id beatae animi officia sequi unde molestiae libero. Quibusdam, minus. Doloribus in, aut, repudiandae commodi assumenda tenetur excepturi a ipsam illum molestias dolore, rem et nostrum libero vero sit iusto sapiente voluptas magni quaerat aliquid mollitia. Quas corporis fugiat ducimus dolorum. Omnis nulla iste cumque dolores dignissimos nam pariatur nihil id suscipit nobis! Inventore unde nulla corrupti architecto ea quia incidunt in ad error minus quo, cumque quasi eos nihil aliquid est aspernatur laborum animi officia iusto? Consectetur quis ratione vitae vel! Assumenda vitae maxime eum consequatur harum! Sed fuga atque, consequuntur tempore unde quam repudiandae praesentium in? Nemo quia cum, ducimus est corporis, magnam eum et natus tenetur id debitis distinctio iste dolores, recusandae fugit voluptatibus veniam eos voluptates soluta adipisci ipsum? Repudiandae magni natus, hic est dolor qui numquam fuga rem repellat porro quos dolores enim commodi, quae reiciendis laborum et inventore nam quo voluptas autem nisi obcaecati illo soluta! Non velit accusamus soluta quas, ducimus ullam asperiores architecto saepe hic nulla distinctio culpa fugiat labore illo laboriosam, fugit molestias officia excepturi at iste doloribus. Neque beatae doloremque provident atque rerum facere. Provident, repellendus iusto sequi aliquam quas tempora at nobis est quasi quibusdam quae fuga quidem in fugit aut, exercitationem aperiam deserunt hic veritatis! Rem impedit a dolorum possimus inventore natus fugiat incidunt praesentium ratione, nostrum quisquam aperiam blanditiis quia culpa libero deleniti est suscipit beatae alias minus, perspiciatis quo saepe quas! Fuga, cupiditate numquam ex, distinctio eligendi saepe eos placeat harum hic quod ea! Quibusdam iusto, dolor similique doloremque doloribus pariatur consequuntur itaque? Excepturi accusamus architecto soluta eveniet illum delectus autem iste, iure obcaecati vel, vitae totam ex, id voluptatem. Illo, sequi ad nostrum praesentium animi exercitationem pariatur cum quis nam tempora quam illum rerum voluptatum molestiae beatae repellendus architecto voluptatem numquam voluptas? Iure quia aliquam tenetur in animi laborum totam cupiditate numquam provident consequatur unde perspiciatis mollitia quibusdam doloremque ut minima, similique a quis tempore optio esse dolorum! A nobis corrupti, vel exercitationem labore veritatis aliquid dolorum vitae quidem et iste adipisci esse quos iusto dolor provident possimus tempore eum asperiores nostrum laborum, velit explicabo aperiam. Numquam blanditiis aliquid, quae porro labore, minus perferendis deserunt vitae consequatur impedit obcaecati repellat! Vitae magni laborum est aliquid, neque temporibus reprehenderit animi accusamus?",
  },
];
